// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyColIN-6y153GihApxTjckRPsO2vyk1aiI',
    appId: '1:101414654781:web:70b148ddd363f5250a6b54',
    messagingSenderId: '101414654781',
    projectId: 'superapp-ee4e1',
    authDomain: 'superapp-ee4e1.firebaseapp.com',
    databaseURL: 'https://superapp-ee4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'superapp-ee4e1.appspot.com',
    measurementId: 'G-YZB0TMBBCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRe37u01b_8xVqC5_QHbqYIWVPKR0FrA',
    appId: '1:101414654781:android:2733aa2e4a6a835f0a6b54',
    messagingSenderId: '101414654781',
    projectId: 'superapp-ee4e1',
    databaseURL: 'https://superapp-ee4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'superapp-ee4e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEG62UR5GV0S8guKfJT0ZCWcb4CouG48o',
    appId: '1:101414654781:ios:0c8e74386988eda10a6b54',
    messagingSenderId: '101414654781',
    projectId: 'superapp-ee4e1',
    databaseURL: 'https://superapp-ee4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'superapp-ee4e1.appspot.com',
    iosBundleId: 'com.example.flutterSuperapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEG62UR5GV0S8guKfJT0ZCWcb4CouG48o',
    appId: '1:101414654781:ios:0c8e74386988eda10a6b54',
    messagingSenderId: '101414654781',
    projectId: 'superapp-ee4e1',
    databaseURL: 'https://superapp-ee4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'superapp-ee4e1.appspot.com',
    iosBundleId: 'com.example.flutterSuperapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyColIN-6y153GihApxTjckRPsO2vyk1aiI',
    appId: '1:101414654781:web:50e596adbcf26a560a6b54',
    messagingSenderId: '101414654781',
    projectId: 'superapp-ee4e1',
    authDomain: 'superapp-ee4e1.firebaseapp.com',
    databaseURL: 'https://superapp-ee4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'superapp-ee4e1.appspot.com',
    measurementId: 'G-S661LE0KFB',
  );

}